version: "3.9"

services:
  web:
    build: .
    container_name: bookmygame_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Force Django to read database info from .env
      DJANGO_SETTINGS_MODULE: bookmygame.settings
    networks:
      - bookmygame_network
    depends_on:
      - mssql
    restart: always
  # Optional: internal MSSQL container (if not using external Akilam server)
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: prime_123$
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - bookmygame_network
    restart: always

volumes:
  mssql_data:

networks:
  bookmygame_network:
    driver: bridge

