version: "3.9"

services:
  web:
    build: .
    container_name: bookmygame_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - bookmygame_network
    restart: always

volumes:
  app1_data:

networks:
  bookmygame_network:
    driver: bridge

