# Generated by Django 5.2.7 on 2025-10-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourtBooking', '0003_courttype_sessionmaster_sportcategory_and_more'),
        ('api', '0002_remove_user_reg_id_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SportCategory',
        ),
    ]
