# Generated by Django 5.2.7 on 2025-10-11 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourtBooking', '0002_alter_sport_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtType',
            fields=[
                ('court_type_id', models.AutoField(db_column='court_type_id', primary_key=True, serialize=False)),
                ('court_type', models.CharField(db_column='court_type', max_length=255)),
            ],
            options={
                'db_table': 'court_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionMaster',
            fields=[
                ('session_Id', models.AutoField(db_column='session_Id', primary_key=True, serialize=False)),
                ('session_name', models.CharField(db_column='session_name', max_length=100)),
            ],
            options={
                'db_table': 'session_Master',
            },
        ),
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('flag', models.BooleanField(db_column='flag', default=True)),
            ],
            options={
                'db_table': 'SportCategory',
            },
        ),
        migrations.AddField(
            model_name='courtmaster',
            name='ratings',
            field=models.FloatField(blank=True, db_column='ratings', default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='courtmaster',
            name='court_type',
            field=models.ForeignKey(db_column='court_type_id', default='Tennis', on_delete=django.db.models.deletion.CASCADE, to='CourtBooking.courttype'),
        ),
        migrations.AddField(
            model_name='slotmaster',
            name='session_Id',
            field=models.ForeignKey(blank=True, db_column='session_Id', default='Morning', on_delete=django.db.models.deletion.CASCADE, to='CourtBooking.sessionmaster'),
        ),
        migrations.CreateModel(
            name='SportMaster',
            fields=[
                ('sport_id', models.AutoField(db_column='sport_Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('flag', models.BooleanField(db_column='flag', default=True)),
                ('image', models.ImageField(blank=True, db_column='image', null=True, upload_to='assets/images/')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='CourtBooking.sportcategory')),
            ],
            options={
                'db_table': 'sport_Master',
            },
        ),
        migrations.AlterField(
            model_name='locationmaster',
            name='sport',
            field=models.ForeignKey(blank=True, db_column='sport_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CourtBooking.sportmaster'),
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
