# Generated by Django 5.2.7 on 2025-10-11 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourtBooking', '0003_courttype_sessionmaster_sportcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportmaster',
            name='category',
            field=models.ForeignKey(db_column='category_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='CourtBooking.sportcategory'),
        ),
    ]
