# Generated by Django 5.2.7 on 2025-10-11 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourtBooking', '0004_alter_sportmaster_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportmaster',
            name='category',
            field=models.ForeignKey(db_column='category_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='CourtBooking.sportcategory'),
        ),
    ]
