# Generated by Django 5.2.7 on 2025-10-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourtBooking', '0005_alter_sportmaster_category'),
        ('api', '0003_delete_sportcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmaster',
            name='reg_Id',
        ),
        migrations.AddField(
            model_name='bookingmaster',
            name='mobile',
            field=models.IntegerField(blank=True, db_column='mobile', null=True),
        ),
        migrations.AlterField(
            model_name='bookingmaster',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usermaster'),
        ),
        migrations.AlterField(
            model_name='locationmaster',
            name='grpLocation',
            field=models.IntegerField(blank=True, db_column='grpLocation_Id', null=True),
        ),
        migrations.AlterField(
            model_name='locationmaster',
            name='reg_Id',
            field=models.ForeignKey(blank=True, db_column='reg_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usermaster'),
        ),
    ]
