# Generated by Django 5.2.7 on 2025-10-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourtBooking', '0006_remove_bookingmaster_reg_id_bookingmaster_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmaster',
            old_name='final_Amt',
            new_name='final_Amount',
        ),
        migrations.AddField(
            model_name='bookingmaster',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, db_column='hold_expires_at', null=True),
        ),
        migrations.AlterField(
            model_name='slotmaster',
            name='Fri',
            field=models.BooleanField(db_column='Fri', default=True),
        ),
        migrations.AlterField(
            model_name='slotmaster',
            name='Mon',
            field=models.BooleanField(db_column='Mon', default=True),
        ),
        migrations.AlterField(
            model_name='slotmaster',
            name='Sat',
            field=models.BooleanField(db_column='Sat', default=True),
        ),
        migrations.AlterField(
            model_name='slotmaster',
            name='Sun',
            field=models.BooleanField(db_column='Sun', default=True),
        ),
        migrations.AlterField(
            model_name='slotmaster',
            name='Thu',
            field=models.BooleanField(db_column='Thu', default=True),
        ),
        migrations.AlterField(
            model_name='slotmaster',
            name='Tue',
            field=models.BooleanField(db_column='Tue', default=True),
        ),
        migrations.AlterField(
            model_name='slotmaster',
            name='Wed',
            field=models.BooleanField(db_column='Wed', default=True),
        ),
    ]
