# Generated by Django 5.2.7 on 2025-10-24 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CourtBooking', '0007_rename_final_amt_bookingmaster_final_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayMaster',
            fields=[
                ('holiday_Id', models.AutoField(db_column='holiday_Id', primary_key=True, serialize=False)),
                ('holiday_date', models.DateField(db_column='holiday_date')),
                ('flag', models.BooleanField(db_column='flag', default=False)),
                ('leave_Type', models.CharField(blank=True, db_column='leave_Type', max_length=100, null=True)),
                ('location_id', models.IntegerField(blank=True, db_column='location_id', null=True)),
                ('Remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
                ('court', models.ForeignKey(db_column='court_id', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='CourtBooking.courtmaster')),
            ],
            options={
                'verbose_name': 'Holiday Master',
                'verbose_name_plural': 'Holiday Masters',
                'db_table': 'holiday_Master',
            },
        ),
    ]
