# Generated by Django 5.2.7 on 2025-10-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_Id', models.AutoField(db_column='sport_Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'sport_Master',
            },
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('location_Id', models.AutoField(db_column='location_Id', primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, db_column='street', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, db_column='mobile', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, db_column='pincode', max_length=10, null=True)),
                ('flag', models.BooleanField(db_column='flag', default=True)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('reg_Id', models.IntegerField(blank=True, db_column='reg_Id', null=True)),
                ('merchantid', models.CharField(blank=True, db_column='merchantid', max_length=255, null=True)),
                ('upi', models.CharField(blank=True, db_column='upi', max_length=255, null=True)),
                ('convenience_Fees', models.FloatField(db_column='convenience_Fees', default=0)),
                ('grpLocation', models.ForeignKey(blank=True, db_column='grpLocation_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CourtBooking.locationmaster')),
                ('sport', models.ForeignKey(blank=True, db_column='sport_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CourtBooking.sport')),
            ],
            options={
                'db_table': 'location_Master',
            },
        ),
        migrations.CreateModel(
            name='CourtMaster',
            fields=[
                ('court_Id', models.AutoField(db_column='court_Id', primary_key=True, serialize=False)),
                ('court_Name', models.CharField(db_column='court_Name', max_length=255)),
                ('court_Count', models.IntegerField(db_column='court_Count', default=0)),
                ('coach_Count', models.IntegerField(db_column='coach_Count', default=0)),
                ('url', models.URLField(blank=True, db_column='url', max_length=500, null=True)),
                ('duration', models.IntegerField(db_column='duration', help_text='Duration in minutes')),
                ('starttime', models.TimeField(db_column='starttime')),
                ('endtime', models.TimeField(db_column='endtime')),
                ('peakhours', models.IntegerField(db_column='peakhours', default=0)),
                ('nonpeakhours', models.IntegerField(db_column='nonpeakhours', default=0)),
                ('flag', models.BooleanField(db_column='flag', default=True)),
                ('user', models.ForeignKey(db_column='user_Id', on_delete=django.db.models.deletion.CASCADE, to='api.usermaster')),
                ('location', models.ForeignKey(db_column='location_Id', on_delete=django.db.models.deletion.CASCADE, to='CourtBooking.locationmaster')),
            ],
            options={
                'db_table': 'court_Master',
            },
        ),
        migrations.CreateModel(
            name='SlotMaster',
            fields=[
                ('slot_Id', models.AutoField(db_column='slot_Id', primary_key=True, serialize=False)),
                ('slot_Name', models.CharField(db_column='slot_Name', max_length=255)),
                ('IsPeak', models.BooleanField(db_column='IsPeak', default=False)),
                ('IsActive', models.BooleanField(db_column='IsActive', default=True)),
                ('Mon', models.BooleanField(db_column='Mon', default=False)),
                ('Tue', models.BooleanField(db_column='Tue', default=False)),
                ('Wed', models.BooleanField(db_column='Wed', default=False)),
                ('Thu', models.BooleanField(db_column='Thu', default=False)),
                ('Fri', models.BooleanField(db_column='Fri', default=False)),
                ('Sat', models.BooleanField(db_column='Sat', default=False)),
                ('Sun', models.BooleanField(db_column='Sun', default=False)),
                ('created_Date', models.DateTimeField(auto_now=True, db_column='created_Date')),
                ('updated_Date', models.DateTimeField(auto_now=True, db_column='updated_Date')),
                ('court', models.ForeignKey(db_column='court_Id', on_delete=django.db.models.deletion.CASCADE, to='CourtBooking.courtmaster')),
                ('created_By', models.ForeignKey(blank=True, db_column='created_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_created_by', to='api.usermaster')),
                ('updated_By', models.ForeignKey(blank=True, db_column='updated_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_updated_by', to='api.usermaster')),
            ],
            options={
                'db_table': 'slot_Master',
            },
        ),
        migrations.CreateModel(
            name='BookingMaster',
            fields=[
                ('book_Id', models.AutoField(db_column='book_Id', primary_key=True, serialize=False)),
                ('book_Date', models.DateField(db_column='book_Date')),
                ('slot_Name', models.CharField(blank=True, db_column='slot_Name', max_length=255, null=True)),
                ('reg_Id', models.IntegerField(blank=True, db_column='reg_Id', null=True)),
                ('discount', models.FloatField(db_column='discount', default=0)),
                ('discount_Amt', models.FloatField(db_column='discount_Amt', default=0)),
                ('actual_Amt', models.FloatField(db_column='actual_Amt', default=0)),
                ('final_Amt', models.FloatField(db_column='final_Amt', default=0)),
                ('payment_Id', models.CharField(blank=True, db_column='payment_Id', max_length=255, null=True)),
                ('flag', models.BooleanField(db_column='flag', default=True)),
                ('created_Date', models.DateTimeField(auto_now=True, db_column='created_Date')),
                ('modified_Date', models.DateTimeField(auto_now=True, db_column='modified_Date')),
                ('modified_By', models.ForeignKey(blank=True, db_column='modified_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_modified_by', to='api.usermaster')),
                ('user', models.ForeignKey(blank=True, db_column='mobile', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usermaster')),
                ('court', models.ForeignKey(db_column='court_Id', on_delete=django.db.models.deletion.CASCADE, to='CourtBooking.courtmaster')),
                ('slot', models.ForeignKey(db_column='slot_Id', on_delete=django.db.models.deletion.CASCADE, to='CourtBooking.slotmaster')),
            ],
            options={
                'db_table': 'booking_Master',
            },
        ),
    ]
