# Generated by Django 5.2.7 on 2025-10-06 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourtBooking', '0001_initial'),
        ('api', '0002_remove_user_reg_id_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.ForeignKey(db_column='name', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='api.sportcategory'),
        ),
    ]
